### ISSUE TITLE
芙蕾雅(上古卷轴)是棍勇里的

### ISSUE THREAD

**Issue by SwakinX** [Zzzzzzyt/MoeRanker#13]

**Comment by Zzzzzzyt** [comment]
e0cdd90 已修，bangumi没图
[芙蕾雅(上古卷轴)](https://zh.moegirl.org.cn/%E8%8A%99%E8%95%BE%E9%9B%85(%E4%B8%8A%E5%8F%A4%E5%8D%B7%E8%BD%B4)) -> None
