### ISSUE TITLE
想问一下作者debug一栏中的含义

### ISSUE THREAD

**Issue by viper-sys** [Zzzzzzyt/MoeRanker#16]
简介里的描述似乎与debug中的数据对不上，想知道debug一栏各数据的含义

**Comment by Zzzzzzyt** [comment]
该属性角色均分(赋分) / 该属性角色数  有无该属性分差  人数修正系数

具体看代码
https://github.com/Zzzzzzyt/MoeRanker/blob/366fbda3e98838fe591d86312eca96365cba6fc0/assets/js/main.js#L690-L692
