### ISSUE TITLE
虚拟歌手部分勘误

### ISSUE THREAD

**Issue by Octives** [Zzzzzzyt/MoeRanker#2]
图片完全错误：奥斯卡、Mite、石棉、Vivi、玄武、JUN、未央、Sachiko、观音菩萨、Chika、琥珀虚颜、Ruby、小冰、莲华、小夜、ROSA、Mew、Rana、高桥、嘟嘟、艾可、Kizuna
混入其他图片：Lily、Oliver、MAYU、MEIKO
特殊：琪亚娜·卡斯兰娜（显示图片为游戏中形象，应为衍生歌姬形象）
范围存疑：金坷垃娘（并无声库，也不被认为是虚拟歌手）

**Comment by Zzzzzzyt** [comment]
这子集问题太多了，数据代表性也很烂，总之我准备直接删掉

**Comment by Zzzzzzyt** [comment]
e0cdd90 禁用了
