### ISSUE TITLE
希望在打分时候少几个层级

### ISSUE THREAD

**Issue by LemPhyth** [Zzzzzzyt/MoeRanker#22]
我感觉我根本不会给角色xp评分（）希望在打分的层面上多进行一些引导，比如0-2分不喜欢，3-5分为还行，6-8分喜欢，9-10分单推这样，我测了几次不同数据集的组合测出来的表去预测其他我知道的作品的时候，xp角色的排名总是差很大，应该是我不会打分（）

**Comment by Zzzzzzyt** [comment]
不是你不会打，这个算法本来就很烂（）
