### ISSUE TITLE
[Bug] 无法计算结果

### ISSUE THREAD

**Issue by Embers-of-the-Fire** [Zzzzzzyt/MoeRanker#27]
## 概述

点击“刷新结果”按钮后无响应。

控制台报错：

```plain
TypeError: Cannot set properties of null (setting '0')
    at main.js:643:19
```

## 浏览器数据

Microsoft Edge 正式版 126.0.2592.56
Google Chrome 正式版 127.0.6533.120

## 原因

https://github.com/Zzzzzzyt/MoeRanker/blob/fdb67ba086c2841eee358213112c3ef83684913f/assets/js/main.js#L641-L645

未初始化的中间变量 `rating`。

**Comment by Zzzzzzyt** [comment]
~~头一回见这么标准的issue还带pr的 感动啊~~

不过这边`rating`应该是全局变量，预测那边的的代码要用的，应该是加了use strict以后坏掉了

我现在身边没有电脑，等回家再看看怎么搞

**Comment by Embers-of-the-Fire** [comment]
> 不过这边`rating`应该是全局变量，预测那边的的代码要用的，应该是加了use strict以后坏掉了

不排除是浏览器特定行为导致的错误。似乎其他浏览器能够正常使用。
