### ISSUE TITLE
图片缺失

### ISSUE THREAD

**Issue by Yzeptgmkb** [Zzzzzzyt/MoeRanker#29]
[赤座灯里]图片缺失
![123](https://github.com/user-attachments/assets/4ff5c920-18fd-40dd-931d-3c832a644b07)

**Comment by Zzzzzzyt** [comment]
这是彩蛋，[bangumi亦如此](https://bgm.tv/character/13004)

**Comment by Yzeptgmkb** [comment]
没看过这个番，现在秒懂😂
