### ISSUE TITLE
舰娘类图片错误太多

### ISSUE THREAD

**Issue by doorouter** [Zzzzzzyt/MoeRanker#3]
不确定是不是因为同时点选了舰c和舰r导致的，映射方式是在萌百检索id然后映射吗？战舰少女（舰r）的图片有80％都给的是舰c甚至没有的，舰娘游戏的同名舰太多了
![Uploading 72BEF1CD-2C39-468C-A477-D1E073067D8A.jpeg…]()

**Comment by happy1041** [comment]
不是因为多选导致的，我只点了舰B还是80％是舰C

**Comment by Professor-Wang** [comment]
一样，我只选了舰b，发现呈现的图片大多都是舰c

**Comment by Zzzzzzyt** [comment]
e0cdd90 已修
不过bangumi上舰B/R的图真的很少，现在只剩几十张了
