### ISSUE TITLE
没有和画风有关的的标签

### ISSUE THREAD

**Issue by turingcat0** [Zzzzzzyt/MoeRanker#30]
对于很多人而言，画风是可以影响喜好程度的一个较大的因素。比如都是萝莉，我会给我喜欢的画风的萝莉打高分，但是会给不喜欢的画风的打低分。但是由于没有画风的标签，程序会认为这些差异是由其他因素引起的。

**Comment by Zzzzzzyt** [comment]
来自bangumi和萌百的数据都不包含画风信息，以已有的数据集这个实在没法做到
萌百的数据还是更多集中在性格特征上，毕竟画风是可以多变的
