### ISSUE TITLE
做多种题库导致结果乱了

### ISSUE THREAD

**Issue by Rlinstar** [Zzzzzzyt/MoeRanker#33]
😭好不容易做了一万题，被之前做马娘专题整上了主角厨、马、马娘等标签debug…
https://pic.imgdb.cn/item/66c0c9e5d9c307b7e9a76837.jpg

**Comment by Zzzzzzyt** [comment]
不是哥们 你真做1w题啊（）
进度文件发一下，我给你删掉做马娘的历史
