### ISSUE TITLE
图片映射错误

### ISSUE THREAD

**Issue by MRSlouzk** [Zzzzzzyt/MoeRanker#39]
碧蓝航线的山城meta图片是错的，给的是山城本体的图而非其meta形态
![QQ20240818-105639](https://github.com/user-attachments/assets/fe3ef774-fe88-4785-9c2b-f82e61f1ddd0)
![QQ20240818-105700](https://github.com/user-attachments/assets/f65a0390-3667-48cd-9f5c-5bd7f69c1e6b)

**Comment by MRSlouzk** [comment]
好像meta的图都有问题，给的都是原角色立绘，Meta和原角色还是有很大区别的

**Comment by Zzzzzzyt** [comment]
这个没办法，bangumi只收录本体
