### ISSUE TITLE
碧蓝航线：飞云 图片错误

### ISSUE THREAD

**Issue by damao-stupid** [Zzzzzzyt/MoeRanker#4]
![Screenshot_20240805_130448](https://github.com/user-attachments/assets/4f7f3083-2ad8-4bbf-92de-00e2bfbc79bb)
![700px-%E9%A3%9E%E4%BA%91%E7%AB%8B%E7%BB%98](https://github.com/user-attachments/assets/eeab8d90-73f2-433e-999d-d64e5c547e52)

**Comment by damao-stupid** [comment]
碧蓝航线系的错图好像有点多。。。

**Comment by Zzzzzzyt** [comment]
Duplicate of #3
