### ISSUE TITLE
不加载图片

### ISSUE THREAD

**Issue by putaoxiaoxue** [Zzzzzzyt/MoeRanker#40]
![Screenshot_20240818_113006_com huawei browser](https://github.com/user-attachments/assets/5760d404-8239-4a03-b915-59ff8fa30f16)
![Screenshot_20240818_113344_com huawei browser](https://github.com/user-attachments/assets/671d597f-0b7e-45d1-ac9e-743c01c9f986)

**Comment by Zzzzzzyt** [comment]
这两个角色在bangumi没有图片，没办法

**Comment by putaoxiaoxue** [comment]
ok



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年08月18日 11:53 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Zzzzzzyt/MoeRanker] 不加载图片 (Issue #40) |

这两个角色在bangumi没有图片，没办法
