### ISSUE TITLE
图片映射错误

### ISSUE THREAD

**Issue by fesefewfe** [Zzzzzzyt/MoeRanker#43]
提高前k张设置时出现的候选图片有较大概率为其他作品的同名角色
如
![弁天](https://github.com/user-attachments/assets/afdb5e58-ffd3-4849-94f1-8da11e15a32f)
弁天（有顶天家族）就同时出现了有顶天家族及福星小子
![image](https://github.com/user-attachments/assets/fa505938-635f-458c-9331-2ab4dfa5043f)
机动战队:艾米中同时出现了机动战队及翠星之加尔刚蒂亚

**Comment by Zzzzzzyt** [comment]
这是正常现象，是匹配算法的局限性
