### ISSUE TITLE
机动战队配图错误

### ISSUE THREAD

**Issue by ealles124** [Zzzzzzyt/MoeRanker#5]
![QQ图片20240805143449](https://github.com/user-attachments/assets/13ceaba0-368c-4888-b43d-befd3aa7e5a3)

**Comment by Zzzzzzyt** [comment]
没错啊
https://zh.moegirl.org.cn/%E6%9C%BA%E5%8A%A8%E6%88%98%E9%98%9F:%E5%B0%BC%E5%A8%85
