### ISSUE TITLE
食蜂操祈的来源错标成了蔚蓝档案

### ISSUE THREAD

**Issue by Fillair19** [Zzzzzzyt/MoeRanker#53]
![image](https://github.com/user-attachments/assets/d39ffdbf-0b3b-472a-95ad-c2d4f0b19606)

正确来源应该是超炮

**Comment by Zzzzzzyt** [comment]
这是萌百把BA联动角色分立页面导致的，有两个食蜂操祈
目前代码没办法识别是同一角色联动还是不同作品同名角色，也没办法合并（）所以先这样吧

**Comment by Zzzzzzyt** [comment]
fixed in 6496ddd
