### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by HL-Takki** [Zzzzzzyt/MoeRanker#6]
图片与“小不点”角色不符
![Screenshot_20240805_144521_com android chrome](https://github.com/user-attachments/assets/3f068f31-5fb4-451f-867f-3cf3a4d1f11a)

**Comment by Zzzzzzyt** [comment]
e0cdd90 已修
[小不点(LoveLive!)](https://zh.moegirl.org.cn/%E5%B0%8F%E4%B8%8D%E7%82%B9(LoveLive!)) -> https://bgm.tv/character/110647
